# -*- mode: ruby -*-
# vi: set ft=ruby :

MONITORING_IP = "192.168.56.11"

Vagrant.configure("2") do |config|
  config.vm.define "monitoring" do |monitoring|
    monitoring.vm.box = "ubuntu/bionic64"
    monitoring.vm.network "private_network", ip: MONITORING_IP
    monitoring.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    monitoring.vm.synced_folder ".", "/vagrant", type: "virtualbox"

    monitoring.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      sudo apt-get update
      sudo apt-get install -y docker-ce
      sudo usermod -aG docker vagrant
    SHELL

    # Budowanie i uruchamianie kontenerów z Prometheusem i Grafaną
    monitoring.vm.provision "shell", privileged: false, inline: <<-SHELL
    cd /vagrant/docker
    # Budowanie obrazu dla Prometheusa
    docker build -f Dockerfile -t monitoring/prometheus .
    # Budowanie obrazu dla Grafany
    docker build -f Dockerfile.grafana -t monitoring/grafana .

    # Uruchomienie Prometheusa
    docker run -d -p 9090:9090 monitoring/prometheus
    # Uruchomienie Grafany
    docker run -d -p 3000:3000 monitoring/grafana
    SHELL
  end
end
